version: "3.8"
services:
  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - PLEASE_SET_PATH_TO_DB_HERE
    ports:
      - 27017:27017
    restart: unless-stopped
